# **1Ô∏è‚É£ Import Libraries**

In [ ]:
import pandas as pd
import numpy as np

# **2Ô∏è‚É£ Load Dataset**

In [ ]:
# üìÇ Load raw dataset
df = pd.read_csv('/content/Coffee Shop Sales.xlsx - Transactions.csv')

# Preview dataset
df.sample(7)

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
81340,81514,5/2/2023,8:27:32,2,5,Lower Manhattan,46,2.50,Tea,Brewed Green tea,Serenity Green Tea Rg
145051,145388,6/27/2023,9:42:29,1,5,Lower Manhattan,58,3.50,Drinking Chocolate,Hot chocolate,Dark chocolate Rg
24084,24141,2/12/2023,17:54:13,2,3,Astoria,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg
15814,15844,1/28/2023,16:46:28,1,3,Astoria,76,3.50,Bakery,Biscotti,Chocolate Chip Biscotti
112883,113145,5/31/2023,7:40:27,3,5,Lower Manhattan,56,2.55,Tea,Brewed Chai tea,Spicy Eye Opener Chai Rg
119151,119413,6/5/2023,16:36:49,2,5,Lower Manhattan,43,3.00,Tea,Brewed herbal tea,Lemon Grass Lg
31606,31663,2/25/2023,10:49:55,1,3,Astoria,77,3.00,Bakery,Scone,Oatmeal Scone

# **3Ô∏è‚É£ Explore Dataset**

In [ ]:
# Shape of dataset
df.shape

(149116, 11)

In [ ]:
# üîç Dataset Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  object
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  object
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  object
 9   product_type      149116 non-null  object
 10  product_detail    149116 non-null  object
dtypes: float64(1), int64(4), object(6)
memory usage: 12.5+ MB

In [ ]:
# üìä Statistical Summary
df.describe()

,transaction_id,transaction_qty,store_id,product_id,unit_price
count,149116.000000,149116.000000,149116.000000,149116.000000,149116.000000
mean,74737.371872,1.438276,5.342063,47.918607,3.382219
std,43153.600016,0.542509,2.074241,17.930020,2.658723
min,1.000000,1.000000,3.000000,1.000000,0.800000
25%,37335.750000,1.000000,3.000000,33.000000,2.500000
50%,74727.500000,1.000000,5.000000,47.000000,3.000000
75%,112094.250000,2.000000,8.000000,60.000000,3.750000
max,149456.000000,8.000000,8.000000,87.000000,45.000000

In [ ]:
# üß© Check Missing Values
df.isnull().sum()

transaction_id      0
transaction_date    0
transaction_time    0
transaction_qty     0
store_id            0
store_location      0
product_id          0
unit_price          0
product_category    0
product_type        0
product_detail      0
dtype: int64

# **4Ô∏è‚É£ Data Cleaning & Transformation**

In [ ]:
# ‚úèÔ∏è Rename Columns for Readability
df = df.rename(columns={
    'transaction_id'   : 'Order_id',
    'transaction_qty'  : 'Quantity',
    'transaction_date' : 'Order_date',
    'transaction_time' : 'Time'
})

In [ ]:
# ‚ûï Add Total_Price Column
df['Total_Price'] = df['Quantity'] * df['unit_price']

In [ ]:
# üóëÔ∏è Drop Unnecessary Columns
df = df.drop(['store_id', 'product_id', 'product_detail'], axis=1)

In [ ]:
# üßπ Drop Missing Values
df = df.dropna()

In [ ]:
# üìÜ Convert Order_date to DateTime
df['Order_date'] = pd.to_datetime(df['Order_date'], errors='coerce')

## **5Ô∏è‚É£ Standardize Text Columns**

In [ ]:
# üé® Standardize string formatting
df['store_location']   = df['store_location'].str.strip().str.title()
df['product_category'] = df['product_category'].str.strip().str.title()
df['product_type']     = df['product_type'].str.strip().str.title()

# **6Ô∏è‚É£ Validate Cleaned Data**

In [ ]:
# ‚úÖ Quick sanity check
print("Final Shape:", df.shape)
print("Null Values:\n", df.isnull().sum())
df.head()

Final Shape: (149116, 9)
Null Values:
 Order_id            0
Order_date          0
Time                0
Quantity            0
store_location      0
unit_price          0
product_category    0
product_type        0
Total_Price         0
dtype: int64

,Order_id,Order_date,Time,Quantity,store_location,unit_price,product_category,product_type,Total_Price
0,1,2023-01-01,7:06:11,2,Lower Manhattan,3.0,Coffee,Gourmet Brewed Coffee,6.0
1,2,2023-01-01,7:08:56,2,Lower Manhattan,3.1,Tea,Brewed Chai Tea,6.2
2,3,2023-01-01,7:14:04,2,Lower Manhattan,4.5,Drinking Chocolate,Hot Chocolate,9.0
3,4,2023-01-01,7:20:24,1,Lower Manhattan,2.0,Coffee,Drip Coffee,2.0
4,5,2023-01-01,7:22:41,2,Lower Manhattan,3.1,Tea,Brewed Chai Tea,6.2

# **7Ô∏è‚É£  Save Cleaned Dataset**

In [ ]:
# üíæ Save cleaned dataset
df.to_csv('Cleaned_Coffee_Sales_Dataset.csv', index=False)

print("‚úÖ Data cleaning complete! Cleaned file saved as 'Cleaned_Coffee_Sales_Dataset.csv'")

‚úÖ Data cleaning complete! Cleaned file saved as 'Cleaned_Coffee_Sales_Dataset.csv'